version: '3.8'

services:
  # PostgreSQL database for development and testing
  postgres:
    image: postgres:15-alpine
    container_name: simpletodo-postgres
    environment:
      POSTGRES_DB: simpletodo
      POSTGRES_USER: todouser
      POSTGRES_PASSWORD: todopass
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/db/init:/docker-entrypoint-initdb.d
    networks:
      - simpletodo-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todouser -d simpletodo"]
      interval: 10s
      timeout: 5s
      retries: 5

  # pgAdmin for database administration (optional)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: simpletodo-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@simpletodo.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - simpletodo-network
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  simpletodo-network:
    driver: bridge
