-- H2 Schema for Development
-- This creates the same table structure as PostgreSQL but optimized for H2

-- Note: H2 automatically creates the table via JPA, but this ensures consistency
-- and allows for custom indexes and constraints

-- Create indexes for performance (H2 syntax)
-- These will be created after the table is auto-generated by JPA
